apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-wordpress-chart.mysql.fullname" . }}
  labels:
    {{- include "my-wordpress-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    {{- include "my-wordpress-chart.mysql.selectorLabels" . | nindent 4 }}
